# Generated by Django 3.2.9 on 2021-11-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_alter_reminder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='end_time',
            field=models.TimeField(default='9:00'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='start_time',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
